### ISSUE TITLE
.DS_Store も git管理対象外に指定する

### ISSUE THREAD

**Issue by dito** [furuhama/rails_tutorial#3]
Finder で開くと勝手にできるやつ
グローバルで対象外にしていい

## 参考
- [グローバルで.gitignoreを適応する](http://qiita.com/katsew/items/5cade12fa743a2f31f25)
- [gitignore に書くべきでないものは gitignore_global へ](http://qiita.com/elzup/items/4c92a2abdab56db3fb4e)

**Comment by furuhama** [comment]
done
